# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-04 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllapotValtozas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uj_statusz', models.CharField(blank=True, choices=[('f', 'Fogadva'), ('g', 'Hibajavítás folyamatba helyezve'), ('h', 'Hibajavítás azonnal nem lehetséges, ajánlatkészítés folyamatban'), ('i', 'Hibajavítás azonnal nem lehetséges, alkatrészre vár'), ('j', 'A hiba javítása elkészült')], default='f', help_text='Hiba Allapot', max_length=1)),
                ('valtozas_datuma', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Hiba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nev', models.CharField(default='', help_text='Adja meg a hiba bejelentő nevét', max_length=200)),
                ('cim', models.CharField(default='', help_text='Adja meg a hiba címét', max_length=200)),
                ('kapcsolattarto_email', models.EmailField(help_text='Ezen az emailen lesz tájékoztatva a hibajavításról', max_length=254)),
                ('leiras', models.TextField(max_length=2000)),
                ('bejelentes_datuma', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('statusz', models.CharField(blank=True, choices=[('f', 'Fogadva'), ('g', 'Hibajavítás folyamatba helyezve'), ('h', 'Hibajavítás azonnal nem lehetséges, ajánlatkészítés folyamatban'), ('i', 'Hibajavítás azonnal nem lehetséges, alkatrészre vár'), ('j', 'A hiba javítása elkészült')], default='f', help_text='Hiba Allapot', max_length=1)),
                ('allapotvaltozasok_szama', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hibák',
                'verbose_name_plural': 'Hibák',
            },
        ),
        migrations.CreateModel(
            name='Visszajelzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzenet', models.TextField(max_length=2000)),
                ('datum', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('hiba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibak.Hiba')),
            ],
            options={
                'verbose_name': 'Visszajelzések',
                'verbose_name_plural': 'Visszajelzések',
            },
        ),
        migrations.AddField(
            model_name='allapotvaltozas',
            name='hiba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hibak.Hiba'),
        ),
    ]
